### ISSUE TITLE
При ререндере /game не отображается canvas

### ISSUE THREAD

**Issue by KrohNic** [dosenk/rsclone#110]
При смене языка или при возвращении в игру с других роутов не отображается canvas.

**Comment by dosenk** [comment]
На каком-то моменте при переходе по роутам теряется parentElement, и по итогу у обьекта класса Game и класса Board он разный.  Поэтому при возвращении в роут Game метод this.board.displayBoard() делает append не в тот parentElement.

**Comment by dosenk** [comment]
const { main, wholeLayout } = createLayoutElements(observer, router); - может быть тут что не так?
