### ISSUE TITLE
Добавить роль клиента отгадывающий/загадывающий

### ISSUE THREAD

**Issue by KrohNic** [dosenk/rsclone#30]
Можно в state добавить свойство, например, role со значениями 'guesser' | 'painter', эти Значения приходят от сервера. В зависимости от полученного значения создается Board нужного типа.

**Comment by dosenk** [comment]
предлагаю это делать в сокете, просто отдельным событием: типо 'game'. На сервере будет храниться либо просто в массиве либо в БД данные о тех кто уже был painter и кто еще нет.

**Comment by vladislavgribkov** [comment]
лучше в массиве, первого брать, - делать ведущим, а потом пушить его в конец, те кто будут подключаться сразу пушить в конец очереди.

**Comment by vladislavgribkov** [comment]
и Board я сделал одним классом, там теперь есть просто флаг: либо хост, либо игрок, от этого просто зависит, прослушивается ли событие на canvas или нет.
