### ISSUE TITLE
Смена роутинга с game на другой

### ISSUE THREAD

**Issue by dosenk** [dosenk/rsclone#50]
При переключении роутов с game нужно отключаться от сокета?
Либо остаемся в сокете?
Если остаемся в сокете, то другие пользователи видят, что мы в игре.

**Comment by vladislavgribkov** [comment]
Да, нужно отключаться. Потому что мало ли чем пользователь занимается, а если он станет ведущим, то все будут ждать, пока он вернется.

**Comment by KrohNic** [comment]
В оригинальной игре пользователя не отключает, все так и ждут, и если он возвращается то есть возможность вернутся в покинутую игру. В socket.io свой массив клиентов где-то внутри, еще повозится надо что бы такую логику сделать.
Поэтому я считаю лучше просто запретить переходы на другие роуты во время игры (отключить ссылки). 
Если при переключении роутов отключаться от сокета, то и на закрытие страницы тоже надо слушателя вешать. А если браузер с ошибкой вылетит как быть?
