### ISSUE TITLE
Логика игры

### ISSUE THREAD

**Issue by dosenk** [dosenk/rsclone#55]
Предлагаю: 
1. Игру делать сразу для все пользователей
2. Игра начинается тогда, когда как минимум два человека перешли в Game.
3. Сервер отслеживает количество подключенных в игре человек и по порядку названачет художника и отгадывающего.
4. Каждый раз, когда пользователь подключается к игре - сервер передает всем играющим данные в виде обьекта: 
`{painter: {}, guessars:[{},{}]}`
5. До того, пока в игре не будет как минимум два игрока будет крутится прелойдер (ожидаем подключения игроков и т.д)
6. Как только в игре появляется второй игрок, сервер берет по порядку слова из БД и отправляет его игроку, который рисует.
7. Все пользователи пишут в чат свои варианты. Сервер через сокет сравнивает с нужным словом и в результате правильного ответа отсылает всем определенные данные (кто угадал, и что было за слово).
8. Сервер(либо с клиента POST запрос) пишет в БД(таблицу со статистикой) кто отгадал и что за слово (что вообще в статитстике будем держать?)
9. Затем опять со 2-го пункта.
Все данные идут через сокет.

Каким образом будем писать логику на клиентах? Какие ваши варианты?

**Comment by KrohNic** [comment]
Статистика как в оригинале: 

1. общее кол-во сыгранных игр
2. игр за художника
3. % отгаданных ответов игроками от сыгранных игр за художника
4. игр за отгадывающего
5. % отгаданных ответов от сыгранных игр за отгадывающего

**Comment by dosenk** [comment]
Может в state будем хранить и board? 
чтобы при переходах по роуту и возврате в игру было видно что там нарисовали?!

**Comment by KrohNic** [comment]
> Может в state будем хранить и board?
> чтобы при переходах по роуту и возврате в игру было видно что там нарисовали?!

можно
