### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by dosenk** [dosenk/rsclone#63]
Возможно удобнее написать универсальный preloader, у которого два статических метода (display, hide) и в, зависимости от роута метод display отображает всегда разный preloader?!

**Comment by KrohNic** [comment]
Сделал preloader в виде функции, которая принимает текст сообщения и рендерит preloader. При смене роута или статуса игры прелоадер удаляется из DOM. Если пользователь возвращается на роут game или статус меняется на GAME_LOADING прелоадер рендерится вновь.
