### ISSUE TITLE
Popup(модальное окно) для выбора слова для художника

### ISSUE THREAD

**Issue by dosenk** [dosenk/rsclone#71]
написать класс для модального окна. В нем: 
- три слова пришедшие с сервера
- можно выбрать слово кликом по нему
- слово отправляется через сокет, либо POStом на сервер

**Comment by KrohNic** [comment]
От сервера придет сокет "game" с 3-мя отобранными словами и actinType: word. Клиент отправляет выбранное слово по сокету "game" и actinType: word.
