### ISSUE TITLE
Чат (доработка)

### ISSUE THREAD

**Issue by dosenk** [dosenk/rsclone#77]
Добавить возможность поставить like похожему сообщению

**Comment by KrohNic** [comment]
Надо написать что слать на сервер и что принимать от него, при данном событии.

**Comment by dosenk** [comment]
Это можно слать определенную строку(сообщение /like/)в событие сокет broadcast и просто на всех клиентах читать это

**Comment by dosenk** [comment]
this.socket.on(EVENT_BROADCAST, (...msg: Array<string>) => {
      const nikName = msg[0];
      const message = msg[1];
      this.printMessage(nikName, message);
    });
