### ISSUE TITLE
Окно с окончанием игры

### ISSUE THREAD

**Issue by dosenk** [dosenk/rsclone#87]
При клике вне окна с окончанием игры срабатывает тоже событие, что и при клике новая игра.
Может лучше чтобы ничего не происходило, а просто окно закрывалось?

**Comment by KrohNic** [comment]
тогда будет пустой экран

**Comment by KrohNic** [comment]
Добавь, то окно которое в начале игры появляется в #88 , чтобы при клике вне окна с окончанием игры появлялось.

**Comment by dosenk** [comment]
Да, отлично.

**Comment by dosenk** [comment]
Я там немного поменял твой gameEnd, добавил туда ещё старт функцию, может как то назови по другому этот класс
